create database Store;
use Store

CREATE TABLE Familias (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    family NVARCHAR(20),
    description NVARCHAR(MAX)
);

CREATE TABLE Products (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(255) NOT NULL,
    Price FLOAT NOT NULL,
    Family_id UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (Family_id) REFERENCES Familias(ID)
);

CREATE TABLE Carritos (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    name VARCHAR(10)
);

CREATE TABLE CarritoProduct (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Carrito_id UNIQUEIDENTIFIER NOT NULL,
    Product_id UNIQUEIDENTIFIER NOT NULL,
    Quantity INT NOT NULL,
    FOREIGN KEY (Carrito_id) REFERENCES Carritos(ID),
    FOREIGN KEY (Product_id) REFERENCES Products(ID)
);

