CREATE TABLE Users (
    ID UNIQUEIDENTIFIER PRIMARY KEY  ,
    Name NVARCHAR(30) NOT NULL,
    Password NVARCHAR(30) NOT NULL,
    Salt NVARCHAR(5) NOT NULL
);

CREATE TABLE Songs (
    ID UNIQUEIDENTIFIER PRIMARY KEY ,
    Name NVARCHAR(30) NOT NULL
    
);

CREATE TABLE Media (
    ID UNIQUEIDENTIFIER PRIMARY KEY ,
    URL NVARCHAR(255) NOT NULL,
    Song_ID UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (Song_ID) REFERENCES Songs(ID) ON DELETE CASCADE
);

CREATE TABLE Playlist (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(30) NOT NULL,
    User_ID UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (User_ID) REFERENCES Users(ID)
);

CREATE TABLE SongPlaylist (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Song_ID UNIQUEIDENTIFIER NOT NULL,
    Playlist_ID UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (Song_ID) REFERENCES Songs(ID),
    FOREIGN KEY (Playlist_ID) REFERENCES Playlist(ID),
    CONSTRAINT unique_song_playlist UNIQUE (Song_ID, Playlist_ID)
);

CREATE TABLE Roles (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Code NUMBER(1) NOT NULL,
    Name NVARCHAR(20) NOT NULL,
    CONSTRAINT unique_code_role UNIQUE (Code)
);

CREATE TABLE UserRoles (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Role_Code NUMBER(1) NOT NULL,
    User_ID UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (Role_Code) REFERENCES Roles(Code),
    FOREIGN KEY (User_ID) REFERENCES Users(ID)
);

CREATE TABLE RolesPermissions (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Permission_Code NVARCHAR(5),
    Role_Code NVARCHAR(5),
    FOREIGN KEY (Permission_Code) REFERENCES Permissions(Code),
    FOREIGN KEY (Role_Code) REFERENCES Roles(Code)
);

CREATE TABLE Permissions (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Code NVARCHAR(5)
    Name NVARCHAR(30)
)


-- SQL per afegir la taula Perfils a la base de dades (Examen)

CREATE TABLE Profiles (
    ID uniqueidentifier PRIMARY KEY,
	Name varchar(100) NULL,
	Description varchar(100) NULL,
	Status varchar(1) NULL,
	FOREIGN KEY (User_ID) REFERENCES Users(ID) -- NO APLICAT A L'API!
);

CREATE TABLE Images (
	ID uniqueidentifier PRIMARY KEY
    Porfile_ID UNIQUEIDENTIFIER NOT NULL,
    URL NVARCHAR(255) NOT NULL,
    FOREIGN KEY (Porfile_ID) REFERENCES Porfiles(ID)
);

CREATE TABLE PorfilesImages (
	ID uniqueidentifier PRIMARY KEY,
	Porfile_ID uniqueidentifier NOT NULL,
	Image_ID uniqueidentifier NOT NULL,
    FOREIGN KEY (Porfile_ID) REFERENCES Porfiles(ID),
    FOREIGN KEY (Image_ID) REFERENCES Images(ID),
    CONSTRAINT unique_porfile_image UNIQUE (Porfile_ID, Image_ID)
);


